"""Non-configurable system constants.

These values are fixed at compile time. Anything that varies between
deployments belongs in config.py.
"""

# --- Event types (SSE) ---
EVENT_PHASE = "phase"
EVENT_TOKEN = "token"
EVENT_ANALYSIS_SNAPSHOT = "analysis_snapshot"
EVENT_ERROR = "error"
EVENT_DONE = "done"

# --- Phase labels ---
PHASE_UNDERSTANDING = "understanding"
PHASE_RETRIEVING = "retrieving"
PHASE_EVALUATING = "evaluating"
PHASE_PREPARING = "preparing"
PHASE_GENERATING = "generating"

# --- Conversation phases (state machine) ---
PHASE_GREETING = "greeting"
PHASE_DISCOVERY = "discovery"
PHASE_EXPLORATION = "exploration"
PHASE_RECOMMENDATION = "recommendation"
PHASE_QUALIFICATION = "qualification"
PHASE_CAPTURE_AND_CLOSE = "capture_and_close"
PHASE_COMPLETING = "completing"
PHASE_COMPLETED = "completed"

# --- Session statuses ---
SESSION_ACTIVE = "active"
SESSION_COMPLETING = "completing"
SESSION_COMPLETED = "completed"
SESSION_ABANDONED = "abandoned"
SESSION_EXPIRED = "expired"
SESSION_TERMINATED = "terminated"

# --- HTTP headers ---
HEADER_CORRELATION_ID = "X-Correlation-Id"
HEADER_RESPONSE_TIME = "X-Response-Time-Ms"
HEADER_RATE_LIMIT_LIMIT = "X-RateLimit-Limit"
HEADER_RATE_LIMIT_REMAINING = "X-RateLimit-Remaining"
HEADER_RATE_LIMIT_RESET = "X-RateLimit-Reset"
HEADER_RETRY_AFTER = "Retry-After"
HEADER_IDEMPOTENCY_KEY = "Idempotency-Key"
HEADER_ADMIN_KEY = "X-Admin-Key"

# --- n8n dispatch headers ---
HEADER_N8N_SECRET = "X-TASC-Secret"
HEADER_N8N_SIGNATURE = "X-TASC-Signature"
HEADER_N8N_TIMESTAMP = "X-TASC-Timestamp"
HEADER_N8N_IDEMPOTENCY = "X-Idempotency-Key"
HEADER_N8N_CORRELATION = "X-Correlation-Id"

# --- Error codes ---
ERR_VALIDATION_ERROR = "VALIDATION_ERROR"
ERR_EMPTY_MESSAGE = "EMPTY_MESSAGE"
ERR_MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG"
ERR_SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
ERR_SESSION_EXPIRED = "SESSION_EXPIRED"
ERR_TURN_IN_PROGRESS = "TURN_IN_PROGRESS"
ERR_ALREADY_COMPLETED = "ALREADY_COMPLETED"
ERR_ALREADY_DISPATCHED = "ALREADY_DISPATCHED"
ERR_CONSULTATION_NOT_FOUND = "CONSULTATION_NOT_FOUND"
ERR_PAYLOAD_INVALID = "PAYLOAD_INVALID"
ERR_RATE_LIMITED = "RATE_LIMITED"
ERR_UNAUTHORIZED = "UNAUTHORIZED"
ERR_PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
ERR_RETRIEVAL_UNAVAILABLE = "RETRIEVAL_UNAVAILABLE"
ERR_TURN_TIMEOUT = "TURN_TIMEOUT"
ERR_CONTENT_BLOCKED = "CONTENT_BLOCKED"
ERR_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
ERR_INTERNAL_ERROR = "INTERNAL_ERROR"

# --- Misc ---
ULID_LENGTH = 26
DEFAULT_LOCALE = "en-US"
SSE_HEARTBEAT_INTERVAL = 15  # seconds
STREAM_MAX_DURATION = 90  # seconds
TURN_LOCK_ACQUIRE_TIMEOUT = 90  # seconds
